apiVersion: apps/v1
kind: Deployment
metadata:
  name: raft-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raft-node
  template:
    metadata:
      labels:
        app: raft-node
    spec:
      containers:
      - name: raft-node
        image: your-registry/raft-node:latest
        ports:
        - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
